##
# DevShop: DevMaster Server with NGINX
#

---
- hosts: all
  user: root
  roles:
    - opendevshop.aegir-user
    - opendevshop.aegir-nginx
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.composer
    - opendevshop.devmaster
